# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c93c5ce1a27aad12ec181ca868182423a21dad74c4f181a0827e031a6efc245d02dcbc856166ff087db7017287fa7f16e353d12ce3a67071d5b7499e29a248de

test:
  secret_key_base: fa6c1140fd8d1eb836b97b4c9ff0f5af48b5b8d37ad1aa08e33ebcc7e42b0b18c279f114e0184c962afff40a79dee17317910e4afb21a9a7573b9c73b079f155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
